/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author sharathreddy
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    VitalSignHistory history;
    public CreateJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblBp = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        lblConscious = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        fieldBp = new javax.swing.JTextField();
        fieldPulse = new javax.swing.JTextField();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle.setText("Create Vital Sign");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        lblDate.setText("Date");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        lblTemperature.setText("Temperature");
        add(lblTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 20));

        lblBp.setText("Blood Pressure");
        add(lblBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        lblPulse.setText("Pulse");
        add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        lblConscious.setText("Conscious Status");
        add(lblConscious, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        add(fieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 120, -1));
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 120, -1));
        add(fieldBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 120, -1));
        add(fieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 120, -1));

        buttonGroup1.add(btnYes);
        btnYes.setSelected(true);
        btnYes.setText("Yes");
        add(btnYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        buttonGroup1.add(btnNo);
        btnNo.setText("No");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    
          String date = fieldDate.getText();
          float temp = Float.parseFloat(fieldTemperature.getText());
          double bp = Double.parseDouble(fieldBp.getText());
          int pulse = Integer.parseInt(fieldPulse.getText());
          boolean isConscious;
          
          if(btnYes.isSelected() ){
              isConscious = true;
           
          }else{
              isConscious = false;
          }
          
          VitalSign vs = history.addNewVital();
          vs.setDate(date);
          vs.setTemperature(temp);
          vs.setBloodPressure(bp);
          vs.setPulse(pulse);
          vs.setIsConcious(isConscious);
          
          JOptionPane.showMessageDialog(this, "New VitalSign added", "Success", JOptionPane.INFORMATION_MESSAGE);
          
          fieldDate.setText("");
          fieldTemperature.setText("");
          fieldBp.setText("");
          fieldPulse.setText("");
          
              
          
        
              
              
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton btnYes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fieldBp;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldPulse;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JLabel lblBp;
    private javax.swing.JLabel lblConscious;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
