/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sharathreddy
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    VitalSignHistory history;
    public ViewJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh;
        populateTable();
    }
    
    private void populateTable() {
        DefaultTableModel model =(DefaultTableModel)tblVital.getModel();
        model.setRowCount(0);
        
        for(VitalSign vs: history.getHistory()){
            
            Object[] row = new Object[5];
            row[0] = vs;
            row[1] = vs.getTemperature();
            row[2] = vs.getBloodPressure();
            row[3] = vs.getPulse();
            row[4] = vs.isIsConcious();
            
            model.addRow(row);
            
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVital = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblBp = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        lblConscious = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        fieldBp = new javax.swing.JTextField();
        fieldPulse = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Temperature", "Blood Pressure", "Pulse", "Conscious Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVital);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 550, 150));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle.setText("View Vital Sign History");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        lblDate.setText("Date");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        lblTemperature.setText("Temperature");
        add(lblTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, 20));

        lblBp.setText("Blood Pressure");
        add(lblBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        lblPulse.setText("Pulse");
        add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        lblConscious.setText("Conscious Status");
        add(lblConscious, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));
        add(fieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 120, -1));
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 120, -1));
        add(fieldBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 120, -1));
        add(fieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 120, -1));
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 120, 30));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVital.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(this,"Please select a row to view", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        VitalSign selectedVital = (VitalSign)model.getValueAt(selectedRow, 0);
        
        if (selectedVital != null){
            fieldDate.setText(selectedVital.getDate());
            fieldTemperature.setText(String.valueOf(selectedVital.getTemperature()));
            fieldBp.setText(String.valueOf(selectedVital.getBloodPressure()));
            fieldPulse.setText(String.valueOf(selectedVital.getPulse()));
            
            if(selectedVital.isIsConcious()){
                lblStatus.setText("Yes");
               
            }else{
                lblStatus.setText("No");
            }
            
        }
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblVital.getSelectedRow();
          if(selectedRow <0){
            JOptionPane.showMessageDialog(this,"Please select a row to delete", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        VitalSign selectedVital = (VitalSign)model.getValueAt(selectedRow, 0);
        
        history.deleteVital(selectedVital);
        
        JOptionPane.showMessageDialog(this, "Vital Sign deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
         
        populateTable();
        
        fieldDate.setText("");
        fieldTemperature.setText("");
        fieldBp.setText("");
        fieldPulse.setText("");
        lblStatus.setText("");
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField fieldBp;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldPulse;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBp;
    private javax.swing.JLabel lblConscious;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblVital;
    // End of variables declaration//GEN-END:variables

   
}
